name: Create an comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump git hub context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
  
